$script_mysql = <<-SCRIPT
   echo ----------------------------UPDATE APT-GET
   apt-get update && \
   echo ----------------------------INSTALL MYSQL
   apt-get install -y mysql-server-5.7 && \
   echo ----------------------------CONFIG MYSQL
   mysql -e "create user 'phpuserZZZ'@'%' identified by 'pass';"
   echo ----------------------------END SCRIPT
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  #---------------------ENCAMINHAMENTO DE PORTAS
  config.vm.network :forwarded_port, guest: 80, host: 8089
  #-----------------------INTERFACE DE REDE
  #config.vm.network "forwarded_port", guest: 80, host: 8089
  #config.vm.network "private_network", ip: "192.168.56.2"
  #config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", ip: "192.168.0.99"
  #---------------------COMANDOS BASH/SHELL
  config.vm.provision "shell",
    inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys" # incrementa
  config.vm.provision "shell", inline: $script_mysql
  config.vm.provision "shell",
    inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf" #sobrescreve
    config.vm.provision "shell",
      inline: "service mysql restart"
  #-----------------SINCRONIZAÇÃO E ACESSO A PASTAS HOST-GUEST
  config.vm.synced_folder "./configs", "/configs" # pasta VM, pasta host - A Referência é a pasta do vagrantfile
  config.vm.synced_folder ".", "/vagrant", disabled: true   #Evita acesso ao vagrantfile

end
