$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 \
  musql -e "create user 'phpuser'@'%' idenfied by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  #---------------------ENCAMINHAMENTO DE PORTAS
  config.vm.network :forwarded_port, guest: 80, host: 8089
  #-----------------------INTERFACE DE REDE
  #config.vm.network "forwarded_port", guest: 80, host: 8089
  #config.vm.network "private_network", ip: "192.168.56.2"
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.network "public_network", type: "dhcp"
  config.vm.network "public_network", ip: "192.168.0.99"
  #---------------------COMANDOS BASH/SHELL
  config.vm.provision "shell",
    inline: "cat /configs/id_bionic.pub  >> .ssh/authorized_keys" # incrementa
    #inline: "cat /configs/id_bionic.pub  > .ssh/authorized_keys" # sobescreve
  config.vm.provision "shell", inline: $script_mysql

  #-----------------SINCRONIZAÇÃO E ACESSO A PASTAS HOST-GUEST
  config.vm.synced_folder "./configs", "/configs"

  #Evita acesso ao vagrantfile
  config.vm.synced_folder ".", "/vagrant", disabled: true


end
